[package]
name = "luxion"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-hal = { version = "1.2.0", features = ["esp32s3"] }
esp-backtrace = { version = "0.20.0", features = [
    "esp32s3",
    "panic-handler",
] }
esp-println = { version = "0.18.0", features = ["esp32s3"] }

embedded-hal = "1.0.0"
libm = "0.2.15"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"